// ============================================
// DRIP — PRODUCT DATABASE (GLOBAL)
// ============================================

window.allProducts = [
    // --- NEW DROPS / TEES ---
    {
        id: 5,
        name: 'CHAI LOVER TEE',
        price: 1399,
        image: 'chai loverfront.jpg',
        imageBack: 'chai loverback.jpg',
        badge: 'CULTURE',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'For the culture. Premium cotton tee celebrating the national fuel.',
        specs: { id: 'DRIP-005', fabric: '100% Cotton', weight: '280 GSM', finish: 'Screen Print', fit: 'Standard' }
    },
    {
        id: 6,
        name: 'FEARLESS TEE',
        price: 1399,
        image: 'fearlessfront.jpg',
        imageBack: 'fearlessback.jpg',
        badge: 'BOLD',
        stock: 18,
        collection: 'new-drops',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Fear is a choice. Make the right one. Heavyweight oversized fit.',
        specs: { id: 'DRIP-006', fabric: 'Cotton Jersey', weight: '300 GSM', finish: 'Puff Print', fit: 'Oversized' }
    },
    {
        id: 7,
        name: 'ILLUMINATI TEE',
        price: 1399,
        image: 'illuminatifront.jpg',
        imageBack: 'illuminatiback.jpg',
        badge: 'MYSTERY',
        stock: 10,
        collection: 'archive',
        weight: 'winter',
        fit: 'boxy',
        availability: 'available',
        desc: 'Hidden in plain sight. Abstract graphic tee with boxy structure.',
        specs: { id: 'DRIP-007', fabric: 'Heavy Cotton', weight: '320 GSM', finish: 'Digital Print', fit: 'Boxy' }
    },
    {
        id: 8,
        name: 'KHAYAL TEE',
        price: 1399,
        image: 'khayalfront.jpg',
        imageBack: 'khayalback.jpg',
        badge: 'ART',
        stock: 14,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'A thought, a vision, a craft. Premium jersey with abstract art.',
        specs: { id: 'DRIP-008', fabric: 'Cotton Jersey', weight: '280 GSM', finish: 'Digital Print', fit: 'Boxy' }
    },
    {
        id: 9,
        name: 'REALITY TEE',
        price: 1399,
        image: 'realityfront.jpg',
        imageBack: 'realityback.jpg',
        badge: 'NEW',
        stock: 22,
        collection: 'new-drops',
        weight: 'winter',
        fit: 'standard',
        availability: 'available',
        desc: 'Face reality. Embrace the grind. Heavyweight structure.',
        specs: { id: 'DRIP-009', fabric: 'Cotton Jersey', weight: '350 GSM', finish: 'Acid Finish', fit: 'Standard' }
    },
    {
        id: 10,
        name: 'SUCCESS TEE',
        price: 1399,
        image: 'successfront.jpg',
        imageBack: 'successfront.jpg',
        badge: 'MOTIVATION',
        stock: 16,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Defined by results. Clean aesthetic with bold typography.',
        specs: { id: 'DRIP-010', fabric: '100% Cotton', weight: '290 GSM', finish: 'Screen Print', fit: 'Standard' }
    },

    // --- HOODIES & LAYERS ---
    {
        id: 11,
        name: 'INNOCENT HOODIE',
        price: 1499,
        image: 'innocent hoodie.jpg',
        imageBack: 'innocent hoodie.jpg',
        badge: 'WINTER',
        stock: 8,
        collection: 'essentials',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Innocence lost, power gained. Heavyweight fleece.',
        specs: { id: 'DRIP-011', fabric: '100% Cotton Fleece', weight: '360 GSM', finish: 'Soft Touch', fit: 'Oversized' }
    },
    {
        id: 12,
        name: 'JAPAN FISH HOODIE',
        price: 1499,
        image: 'japan fish hoodie.jpg',
        imageBack: 'japan fish hoodie.jpg',
        badge: 'RARE',
        stock: 5,
        collection: 'archive',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Irezumi inspired artwork on our heaviest fleece blank.',
        specs: { id: 'DRIP-012', fabric: 'French Terry', weight: '400 GSM', finish: 'Embroidery', fit: 'Oversized' }
    },

    // --- GRAPHIC TEES (SINGLE IMAGE) ---
    {
        id: 13,
        name: 'DEKH MAGAR PYAR SE',
        price: 1399,
        image: 'dekh magar pyar se.jpg',
        imageBack: 'dekh magar pyar se.jpg',
        badge: 'STREET',
        stock: 25,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Truck art aesthetics meets modern streetwear.',
        specs: { id: 'DRIP-013', fabric: '100% Cotton', weight: '260 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 14,
        name: 'DREAM TEE',
        price: 1399,
        image: 'dream.jpg',
        imageBack: 'dream.jpg',
        badge: 'MINIMAL',
        stock: 30,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Dream big. Dress better.',
        specs: { id: 'DRIP-014', fabric: 'Cotton', weight: '280 GSM', finish: 'Soft', fit: 'Standard' }
    },
    {
        id: 15,
        name: 'FEELING FINE',
        price: 1399,
        image: 'feelingfine.jpg',
        imageBack: 'feelingfine.jpg',
        badge: 'VIBE',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'relaxed',
        availability: 'available',
        desc: 'State of mind. State of dress.',
        specs: { id: 'DRIP-015', fabric: 'Cotton Blend', weight: '270 GSM', finish: 'Wash', fit: 'Relaxed' }
    },
    {
        id: 16,
        name: 'IF TEE',
        price: 1399,
        image: 'if.jpg',
        imageBack: 'if.jpg',
        badge: 'POETRY',
        stock: 15,
        collection: 'archive',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Kipling inspired. Industrial execution.',
        specs: { id: 'DRIP-016', fabric: 'Cotton', weight: '280 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 17,
        name: 'ITS MY ADRENALINE',
        price: 1399,
        image: 'its my adrealanine.jpg',
        imageBack: 'its my adrealanine.jpg',
        badge: 'SPORT',
        stock: 12,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'athletic',
        availability: 'available',
        desc: 'Fuel specifically for the chase.',
        specs: { id: 'DRIP-017', fabric: 'Performance Cotton', weight: '290 GSM', finish: 'Dri-Fit', fit: 'Athletic' }
    },
    {
        id: 18,
        name: 'KHALLAS TEE',
        price: 1399,
        image: 'khallas.jpg',
        imageBack: 'khallas.jpg',
        badge: 'FINAL',
        stock: 5,
        collection: 'archive',
        weight: 'summer',
        fit: 'boxy',
        availability: 'archived',
        desc: 'The end of the line. Final production run.',
        specs: { id: 'DRIP-018', fabric: 'Cotton', weight: '300 GSM', finish: 'Distressed', fit: 'Boxy' }
    },
    {
        id: 19,
        name: 'ONE LOVE',
        price: 1399,
        image: 'one love.jpg',
        imageBack: 'one love.jpg',
        badge: 'UNITY',
        stock: 25,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Unity in design. Harmony in fit.',
        specs: { id: 'DRIP-019', fabric: 'Cotton', weight: '280 GSM', finish: 'Screen', fit: 'Standard' }
    },
    {
        id: 20,
        name: 'ROLEX TEE',
        price: 1399,
        image: 'rolex.jpg',
        imageBack: 'rolex.jpg',
        badge: 'LUXURY',
        stock: 8,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Timeless luxury graphic.',
        specs: { id: 'DRIP-020', fabric: 'Premium Cotton', weight: '320 GSM', finish: 'Gold Foil', fit: 'Standard' }
    },
    {
        id: 21,
        name: 'SAMURAI TEE',
        price: 1399,
        image: 'samurai.jpg',
        imageBack: 'samurai.jpg',
        badge: 'WARRIOR',
        stock: 10,
        collection: 'archive',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Bushido code. Streetwear execution.',
        specs: { id: 'DRIP-021', fabric: 'Heavy Cotton', weight: '340 GSM', finish: 'Print', fit: 'Oversized' }
    },
    {
        id: 22,
        name: 'TOKYO TEE',
        price: 1399,
        image: 'tokyo.jpg',
        imageBack: 'tokyo.jpg',
        badge: 'CITY',
        stock: 18,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'Neotokyo aesthetics.',
        specs: { id: 'DRIP-022', fabric: 'Cotton', weight: '300 GSM', finish: 'Print', fit: 'Boxy' }
    },
    {
        id: 23,
        name: 'URDU SHER',
        price: 1399,
        image: 'urdu sher.jpg',
        imageBack: 'urdu sher.jpg',
        badge: 'POETRY',
        stock: 22,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Classic poetry in motion.',
        specs: { id: 'DRIP-023', fabric: 'Cotton', weight: '270 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 24,
        name: 'WORLDWIDE TEE',
        price: 1399,
        image: 'worldwide.jpg',
        imageBack: 'worldwide.jpg',
        badge: 'GLOBAL',
        stock: 14,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'oversized',
        availability: 'available',
        desc: 'Global shipping. Universal appeal.',
        specs: { id: 'DRIP-024', fabric: 'Cotton', weight: '310 GSM', finish: 'Puff', fit: 'Oversized' }
    },

    // --- NEW PRODUCTS ADDED PER REQUEST ---
    {
        id: 30,
        name: '911 TEE',
        price: 1399,
        image: '911.jpg',
        imageBack: '911.jpg',
        badge: 'STREET',
        stock: 15,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Precision in motion. The legendary 911 graphic.',
        specs: { id: 'DRIP-030', fabric: '100% Cotton', weight: '280 GSM', finish: 'Digital Print', fit: 'Standard' }
    },
    {
        id: 31,
        name: 'BMW TEE',
        price: 1399,
        image: 'bmw.jpg',
        imageBack: 'bmw.jpg',
        badge: 'SPORT',
        stock: 12,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'relaxed',
        availability: 'available',
        desc: 'Ultimate driving machine, ultimate wearing comfort.',
        specs: { id: 'DRIP-031', fabric: 'Cotton Jersey', weight: '290 GSM', finish: 'Screen Print', fit: 'Relaxed' }
    },
    {
        id: 32,
        name: 'CARDS TEE',
        price: 1399,
        image: 'cards.jpg',
        imageBack: 'cards.jpg',
        badge: 'BOLD',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Play your cards right. High-stakes aesthetic.',
        specs: { id: 'DRIP-032', fabric: 'Cotton', weight: '280 GSM', finish: 'Digital Print', fit: 'Standard' }
    },
    {
        id: 33,
        name: 'DEATHNOTE TEE',
        price: 1399,
        image: 'deathnote.jpg',
        imageBack: 'deathnote.jpg',
        badge: 'ANIME',
        stock: 18,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'The power is in your hands. Minimalist anime design.',
        specs: { id: 'DRIP-033', fabric: 'Cotton', weight: '300 GSM', finish: 'High Density Print', fit: 'Boxy' }
    },
    {
        id: 34,
        name: 'DIRTY HONEY TEE',
        price: 1399,
        image: 'dirty honey.jpg',
        imageBack: 'dirty honey.jpg',
        badge: 'VIBE',
        stock: 14,
        collection: 'archive',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Sweet but edgy. Premium distressed look.',
        specs: { id: 'DRIP-034', fabric: 'Cotton', weight: '270 GSM', finish: 'Washed', fit: 'Standard' }
    },
    {
        id: 35,
        name: 'DOPE TEE',
        price: 1399,
        image: 'dope.jpg',
        imageBack: 'dope.jpg',
        badge: 'STREET',
        stock: 25,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Simply dope. Minimal typography for maximal impact.',
        specs: { id: 'DRIP-035', fabric: '100% Cotton', weight: '280 GSM', finish: 'Screen Print', fit: 'Standard' }
    },
    {
        id: 36,
        name: 'MINDSET TEE',
        price: 1399,
        image: 'mindset.jpg',
        imageBack: 'mindset.jpg',
        badge: 'CORE',
        stock: 30,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'It begins in the mind. The essential grind tee.',
        specs: { id: 'DRIP-036', fabric: 'Cotton', weight: '280 GSM', finish: 'Puff Print', fit: 'Standard' }
    },
    {
        id: 37,
        name: 'NO FEAR TEE',
        price: 1399,
        image: 'no fear.jpg',
        imageBack: 'no fear.jpg',
        badge: 'BOLD',
        stock: 22,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'oversized',
        availability: 'available',
        desc: 'Unstoppable. Unbreakable. Fearless.',
        specs: { id: 'DRIP-037', fabric: 'Cotton', weight: '310 GSM', finish: 'Print', fit: 'Oversized' }
    },
    {
        id: 38,
        name: 'PIRATE TEE',
        price: 1399,
        image: 'pirate.jpg',
        imageBack: 'pirate.jpg',
        badge: 'RARE',
        stock: 10,
        collection: 'archive',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'Rebel soul. Seafaring aesthetic.',
        specs: { id: 'DRIP-038', fabric: 'Heavy Cotton', weight: '320 GSM', finish: 'Digital Print', fit: 'Boxy' }
    },
    {
        id: 39,
        name: 'SUPRA TEE',
        price: 1399,
        image: 'supra.jpg',
        imageBack: 'supra.jpg',
        badge: 'SPORT',
        stock: 12,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'JDM Legend. The 2JZ heart on your chest.',
        specs: { id: 'DRIP-039', fabric: 'Cotton', weight: '290 GSM', finish: 'Screen Print', fit: 'Standard' }
    },
    {
        id: 40,
        name: 'TRUCK ART TEE',
        price: 1399,
        image: 'truck art.jpg',
        imageBack: 'truck art.jpg',
        badge: 'CULTURE',
        stock: 18,
        collection: 'essentials',
        weight: 'summer',
        fit: 'relaxed',
        availability: 'available',
        desc: 'Vibrant tradition meets modern street.',
        specs: { id: 'DRIP-040', fabric: 'Cotton Jersey', weight: '280 GSM', finish: 'Digital Print', fit: 'Relaxed' }
    },
    {
        id: 41,
        name: 'TRUST TEE',
        price: 1399,
        image: 'trust.jpg',
        imageBack: 'trust.jpg',
        badge: 'CORE',
        stock: 15,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Trust the process. Trust the drip.',
        specs: { id: 'DRIP-041', fabric: 'Cotton', weight: '280 GSM', finish: 'Screen Print', fit: 'Standard' }
    },
    {
        id: 42,
        name: 'ACID WASH TEE',
        price: 2199,
        image: 'ACID WASH.png',
        imageBack: 'ACID WASH.png',
        badge: 'PREMIUM',
        stock: 10,
        collection: 'new-drops',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Premium acid wash finish for that vintage streetwear vibe.',
        specs: { id: 'DRIP-042', fabric: 'Heavy Cotton', weight: '350 GSM', finish: 'Acid Wash', fit: 'Oversized' }
    },
    {
        id: 43,
        name: 'DROP SHOULDER TEE',
        price: 1399,
        image: 'DROP-SHOULDER.png',
        imageBack: 'DROP-SHOULDER.png',
        badge: 'TRENDING',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'oversized',
        availability: 'available',
        desc: 'Classic drop shoulder silhouette for effortless style.',
        specs: { id: 'DRIP-043', fabric: 'Cotton', weight: '280 GSM', finish: 'Standard', fit: 'Oversized' }
    },
    {
        id: 44,
        name: 'GOLD ACID TEE',
        price: 2199,
        image: 'goldacid.jpg',
        imageBack: 'goldacid.jpg',
        badge: 'EXCLUSIVE',
        stock: 5,
        collection: 'archive',
        weight: 'winter',
        fit: 'boxy',
        availability: 'available',
        desc: 'Gilded age. Acid wash meets gold foil accents.',
        specs: { id: 'DRIP-044', fabric: 'Heavy Cotton', weight: '340 GSM', finish: 'Gold Foil + Acid', fit: 'Boxy' }
    },
    {
        id: 45,
        name: 'COTTON JERSEY',
        price: 2199,
        image: 'cottonjersey.jpg',
        imageBack: 'cottonjersey.jpg',
        badge: 'ELITE',
        stock: 12,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'The highest grade cotton jersey ever produced.',
        specs: { id: 'DRIP-045', fabric: 'Supima Cotton', weight: '300 GSM', finish: 'Silk Touch', fit: 'Standard' }
    },
    {
        id: 46,
        name: 'HEAVYWEIGHT TEE',
        price: 1399,
        image: 'HEAVYWEIGHT.png',
        imageBack: 'HEAVYWEIGHT.png',
        badge: 'CORE',
        stock: 25,
        collection: 'essentials',
        weight: 'winter',
        fit: 'boxy',
        availability: 'available',
        desc: 'Bulletproof construction. Our heaviest tee yet.',
        specs: { id: 'DRIP-046', fabric: 'Heavy Cotton', weight: '400 GSM', finish: 'Standard', fit: 'Boxy' }
    },
    {
        id: 47,
        name: 'KALAKAR TEE',
        price: 1399,
        image: 'kalakar.jpg',
        imageBack: 'kalakar.jpg',
        badge: 'ART',
        stock: 15,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'The artist within. Creative expression in every thread.',
        specs: { id: 'DRIP-047', fabric: 'Cotton', weight: '280 GSM', finish: 'Print', fit: 'Standard' }
    },

    // --- ACCESSORIES & GROOMING ---
    {
        id: 25,
        name: 'RS CHRONO WATCH',
        price: 1800,
        image: 'rs chrono.jpg',
        imageBack: 'rs chrono.jpg',
        badge: 'TIMEPIECE',
        stock: 3,
        collection: 'archive',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Precision chronograph. Limited edition timepiece.',
        specs: { id: 'DRIP-ACC-01', fabric: 'Stainless Steel', weight: '180g', finish: 'Brushed', fit: 'Adjustable' }
    },
    {
        id: 26,
        name: 'UNZ WATCH',
        price: 1800,
        image: 'unzwatch.jpg',
        imageBack: 'unzwatch.jpg',
        badge: 'CLASSIC',
        stock: 4,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Minimalist dial. Maximum impact.',
        specs: { id: 'DRIP-ACC-02', fabric: 'Leather/Steel', weight: '160g', finish: 'Polished', fit: 'Standard' }
    },
    {
        id: 27,
        name: 'WATCH AURA',
        price: 1800,
        image: 'watch aura.jpg',
        imageBack: 'watch aura.jpg',
        badge: 'PREMIUM',
        stock: 2,
        collection: 'archive',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Gold plated elegance.',
        specs: { id: 'DRIP-ACC-03', fabric: 'Gold Plated', weight: '190g', finish: 'Gold', fit: 'Adjustable' }
    },
    {
        id: 28,
        name: 'SEA SALT SPRAY',
        price: 1299,
        image: 'sea salt spray.jpg',
        imageBack: 'sea salt spray.jpg',
        badge: 'GROOMING',
        stock: 50,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Instant texture and volume. Matte finish beach look.',
        specs: { id: 'DRIP-GRM-01', fabric: 'Liquid', weight: '200ml', finish: 'Matte', fit: 'N/A' }
    },
    {
        id: 29,
        name: 'TEXTURE POWDER',
        price: 1199,
        image: 'texture powder.jpg',
        imageBack: 'texture powder.jpg',
        badge: 'GROOMING',
        stock: 45,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Gravity defying hold. Invisible finish.',
        specs: { id: 'DRIP-GRM-02', fabric: 'Powder', weight: '20g', finish: 'Matte', fit: 'N/A' }
    }

];

window.filteredProducts = [...allProducts];
