// ============================================
// DRIP — PRODUCT DATABASE (GLOBAL)
// ============================================

window.allProducts = [
    // --- NEW DROPS / TEES ---
    {
        id: 5,
        name: 'CHAI LOVER TEE',
        price: 4200,
        image: 'chai loverfront.jpg',
        imageBack: 'chai loverback.jpg',
        badge: 'CULTURE',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'For the culture. Premium cotton tee celebrating the national fuel.',
        specs: { id: 'DRIP-005', fabric: '100% Cotton', weight: '280 GSM', finish: 'Screen Print', fit: 'Standard' }
    },
    {
        id: 6,
        name: 'FEARLESS TEE',
        price: 4500,
        image: 'fearlessfront.jpg',
        imageBack: 'fearlessback.jpg',
        badge: 'BOLD',
        stock: 18,
        collection: 'new-drops',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Fear is a choice. Make the right one. Heavyweight oversized fit.',
        specs: { id: 'DRIP-006', fabric: 'Cotton Jersey', weight: '300 GSM', finish: 'Puff Print', fit: 'Oversized' }
    },
    {
        id: 7,
        name: 'ILLUMINATI TEE',
        price: 4800,
        image: 'illuminatifront.jpg',
        imageBack: 'illuminatiback.jpg',
        badge: 'MYSTERY',
        stock: 10,
        collection: 'archive',
        weight: 'winter',
        fit: 'boxy',
        availability: 'available',
        desc: 'Hidden in plain sight. Abstract graphic tee with boxy structure.',
        specs: { id: 'DRIP-007', fabric: 'Heavy Cotton', weight: '320 GSM', finish: 'Digital Print', fit: 'Boxy' }
    },
    {
        id: 8,
        name: 'KHAYAL TEE',
        price: 4800,
        image: 'khayalfront.jpg',
        imageBack: 'khayalback.jpg',
        badge: 'ART',
        stock: 14,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'A thought, a vision, a craft. Premium jersey with abstract art.',
        specs: { id: 'DRIP-008', fabric: 'Cotton Jersey', weight: '280 GSM', finish: 'Digital Print', fit: 'Boxy' }
    },
    {
        id: 9,
        name: 'REALITY TEE',
        price: 4800,
        image: 'realityfront.jpg',
        imageBack: 'realityback.jpg',
        badge: 'NEW',
        stock: 22,
        collection: 'new-drops',
        weight: 'winter',
        fit: 'standard',
        availability: 'available',
        desc: 'Face reality. Embrace the grind. Heavyweight structure.',
        specs: { id: 'DRIP-009', fabric: 'Cotton Jersey', weight: '350 GSM', finish: 'Acid Finish', fit: 'Standard' }
    },
    {
        id: 10,
        name: 'SUCCESS TEE',
        price: 4500,
        image: 'successfront.jpg',
        imageBack: 'successfront.jpg',
        badge: 'MOTIVATION',
        stock: 16,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Defined by results. Clean aesthetic with bold typography.',
        specs: { id: 'DRIP-010', fabric: '100% Cotton', weight: '290 GSM', finish: 'Screen Print', fit: 'Standard' }
    },

    // --- HOODIES & LAYERS ---
    {
        id: 11,
        name: 'INNOCENT HOODIE',
        price: 7500,
        image: 'innocent hoodie.jpg',
        imageBack: 'innocent hoodie.jpg',
        badge: 'WINTER',
        stock: 8,
        collection: 'essentials',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Innocence lost, power gained. Heavyweight fleece.',
        specs: { id: 'DRIP-011', fabric: '100% Cotton Fleece', weight: '360 GSM', finish: 'Soft Touch', fit: 'Oversized' }
    },
    {
        id: 12,
        name: 'JAPAN FISH HOODIE',
        price: 7800,
        image: 'japan fish hoodie.jpg',
        imageBack: 'japan fish hoodie.jpg',
        badge: 'RARE',
        stock: 5,
        collection: 'archive',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Irezumi inspired artwork on our heaviest fleece blank.',
        specs: { id: 'DRIP-012', fabric: 'French Terry', weight: '400 GSM', finish: 'Embroidery', fit: 'Oversized' }
    },

    // --- GRAPHIC TEES (SINGLE IMAGE) ---
    {
        id: 13,
        name: 'DEKH MAGAR PYAR SE',
        price: 3800,
        image: 'dekh magar pyar se.jpg',
        imageBack: 'dekh magar pyar se.jpg',
        badge: 'STREET',
        stock: 25,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Truck art aesthetics meets modern streetwear.',
        specs: { id: 'DRIP-013', fabric: '100% Cotton', weight: '260 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 14,
        name: 'DREAM TEE',
        price: 4000,
        image: 'dream.jpg',
        imageBack: 'dream.jpg',
        badge: 'MINIMAL',
        stock: 30,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Dream big. Dress better.',
        specs: { id: 'DRIP-014', fabric: 'Cotton', weight: '280 GSM', finish: 'Soft', fit: 'Standard' }
    },
    {
        id: 15,
        name: 'FEELING FINE',
        price: 4000,
        image: 'feelingfine.jpg',
        imageBack: 'feelingfine.jpg',
        badge: 'VIBE',
        stock: 20,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'relaxed',
        availability: 'available',
        desc: 'State of mind. State of dress.',
        specs: { id: 'DRIP-015', fabric: 'Cotton Blend', weight: '270 GSM', finish: 'Wash', fit: 'Relaxed' }
    },
    {
        id: 16,
        name: 'IF TEE',
        price: 4000,
        image: 'if.jpg',
        imageBack: 'if.jpg',
        badge: 'POETRY',
        stock: 15,
        collection: 'archive',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Kipling inspired. Industrial execution.',
        specs: { id: 'DRIP-016', fabric: 'Cotton', weight: '280 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 17,
        name: 'ITS MY ADRENALINE',
        price: 4200,
        image: 'its my adrealanine.jpg',
        imageBack: 'its my adrealanine.jpg',
        badge: 'SPORT',
        stock: 12,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'athletic',
        availability: 'available',
        desc: 'Fuel specifically for the chase.',
        specs: { id: 'DRIP-017', fabric: 'Performance Cotton', weight: '290 GSM', finish: 'Dri-Fit', fit: 'Athletic' }
    },
    {
        id: 18,
        name: 'KHALLAS TEE',
        price: 3800,
        image: 'khallas.jpg',
        imageBack: 'khallas.jpg',
        badge: 'FINAL',
        stock: 5,
        collection: 'archive',
        weight: 'summer',
        fit: 'boxy',
        availability: 'archived',
        desc: 'The end of the line. Final production run.',
        specs: { id: 'DRIP-018', fabric: 'Cotton', weight: '300 GSM', finish: 'Distressed', fit: 'Boxy' }
    },
    {
        id: 19,
        name: 'ONE LOVE',
        price: 4200,
        image: 'one love.jpg',
        imageBack: 'one love.jpg',
        badge: 'UNITY',
        stock: 25,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Unity in design. Harmony in fit.',
        specs: { id: 'DRIP-019', fabric: 'Cotton', weight: '280 GSM', finish: 'Screen', fit: 'Standard' }
    },
    {
        id: 20,
        name: 'ROLEX TEE',
        price: 5500,
        image: 'rolex.jpg',
        imageBack: 'rolex.jpg',
        badge: 'LUXURY',
        stock: 8,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Timeless luxury graphic.',
        specs: { id: 'DRIP-020', fabric: 'Premium Cotton', weight: '320 GSM', finish: 'Gold Foil', fit: 'Standard' }
    },
    {
        id: 21,
        name: 'SAMURAI TEE',
        price: 4800,
        image: 'samurai.jpg',
        imageBack: 'samurai.jpg',
        badge: 'WARRIOR',
        stock: 10,
        collection: 'archive',
        weight: 'winter',
        fit: 'oversized',
        availability: 'available',
        desc: 'Bushido code. Streetwear execution.',
        specs: { id: 'DRIP-021', fabric: 'Heavy Cotton', weight: '340 GSM', finish: 'Print', fit: 'Oversized' }
    },
    {
        id: 22,
        name: 'TOKYO TEE',
        price: 4500,
        image: 'tokyo.jpg',
        imageBack: 'tokyo.jpg',
        badge: 'CITY',
        stock: 18,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'boxy',
        availability: 'available',
        desc: 'Neotokyo aesthetics.',
        specs: { id: 'DRIP-022', fabric: 'Cotton', weight: '300 GSM', finish: 'Print', fit: 'Boxy' }
    },
    {
        id: 23,
        name: 'URDU SHER',
        price: 4000,
        image: 'urdu sher.jpg',
        imageBack: 'urdu sher.jpg',
        badge: 'POETRY',
        stock: 22,
        collection: 'essentials',
        weight: 'summer',
        fit: 'standard',
        availability: 'available',
        desc: 'Classic poetry in motion.',
        specs: { id: 'DRIP-023', fabric: 'Cotton', weight: '270 GSM', finish: 'Print', fit: 'Standard' }
    },
    {
        id: 24,
        name: 'WORLDWIDE TEE',
        price: 4500,
        image: 'worldwide.jpg',
        imageBack: 'worldwide.jpg',
        badge: 'GLOBAL',
        stock: 14,
        collection: 'new-drops',
        weight: 'summer',
        fit: 'oversized',
        availability: 'available',
        desc: 'Global shipping. Universal appeal.',
        specs: { id: 'DRIP-024', fabric: 'Cotton', weight: '310 GSM', finish: 'Puff', fit: 'Oversized' }
    },

    // --- ACCESSORIES & GROOMING ---
    {
        id: 25,
        name: 'RS CHRONO WATCH',
        price: 2000,
        image: 'rs chrono.jpg',
        imageBack: 'rs chrono.jpg',
        badge: 'TIMEPIECE',
        stock: 3,
        collection: 'archive',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Precision chronograph. Limited edition timepiece.',
        specs: { id: 'DRIP-ACC-01', fabric: 'Stainless Steel', weight: '180g', finish: 'Brushed', fit: 'Adjustable' }
    },
    {
        id: 26,
        name: 'UNZ WATCH',
        price: 2000,
        image: 'unzwatch.jpg',
        imageBack: 'unzwatch.jpg',
        badge: 'CLASSIC',
        stock: 4,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Minimalist dial. Maximum impact.',
        specs: { id: 'DRIP-ACC-02', fabric: 'Leather/Steel', weight: '160g', finish: 'Polished', fit: 'Standard' }
    },
    {
        id: 27,
        name: 'WATCH AURA',
        price: 2000,
        image: 'watch aura.jpg',
        imageBack: 'watch aura.jpg',
        badge: 'PREMIUM',
        stock: 2,
        collection: 'archive',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Gold plated elegance.',
        specs: { id: 'DRIP-ACC-03', fabric: 'Gold Plated', weight: '190g', finish: 'Gold', fit: 'Adjustable' }
    },
    {
        id: 28,
        name: 'SEA SALT SPRAY',
        price: 2200,
        image: 'sea salt spray.jpg',
        imageBack: 'sea salt spray.jpg',
        badge: 'GROOMING',
        stock: 50,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Instant texture and volume. Matte finish beach look.',
        specs: { id: 'DRIP-GRM-01', fabric: 'Liquid', weight: '200ml', finish: 'Matte', fit: 'N/A' }
    },
    {
        id: 29,
        name: 'TEXTURE POWDER',
        price: 1800,
        image: 'texture powder.jpg',
        imageBack: 'texture powder.jpg',
        badge: 'GROOMING',
        stock: 45,
        collection: 'essentials',
        weight: 'n/a',
        fit: 'n/a',
        availability: 'available',
        desc: 'Gravity defying hold. Invisible finish.',
        specs: { id: 'DRIP-GRM-02', fabric: 'Powder', weight: '20g', finish: 'Matte', fit: 'N/A' }
    }
];

window.filteredProducts = [...allProducts];
